SUCCESS_REMOVE = {"success": "Robô removido"}
SUCCESS_ADD = {"success": "Robô adicionado"}
SUCCESS_START = {"success": "Robô inicializado"}
SUCCESS_STOP = {"success": "Robô pausado"}
SUCCESS_UPDATE = {"success": "Robô atualizado"}
RESOURCE_NOT_FOUND = {"error": "Nenhum registro encontrado"}
ERROR_START = {"error": "Não foi possível inicializar o robô"}
ERROR_STOP = {"error": "Não foi possível pausar o robô"}
ERROR_UNCREATED_ROBOT = {"error": "Não foi possível criar o robô"}
ERROR_UNDELETED_ROBOT = {"error": "Não foi possível deletar o robô"}
ERROR_NOT_UPDATED_ROBOT = {"error": "Não foi possível atualizar o robô"}
